name: Build Executables

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter psycopg2-binary pillow pywin32 pyinstaller tkcalendar babel

    - name: Build GERAR_CATALOGO
      run: |
        pyinstaller --noconsole --onefile --name GERAR_CATALOGO gerar_catalogo.py

    - name: Build VISUALIZAR_CATALOGO
      run: |
        pyinstaller --noconsole --onefile --name VISUALIZAR_CATALOGO visualizar_catalogo.py

    - name: Build APP_GESTAO_ENCARTE
      run: |
        pyinstaller --onefile --collect-all customtkinter --collect-all tkcalendar --collect-all babel --name APP_GESTAO_ENCARTE app_gestao_encarte.py

    - name: Upload Executables
      uses: actions/upload-artifact@v4
      with:
        name: Executaveis_Encarte
        path: dist/*.exe
