name: Compilar Executaveis

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow

    - name: Gerar Executavel do Gerador
      run: |
        pyinstaller --noconfirm --onefile --windowed --name GERAR_CATALOGO gerar_catalogo.py

    - name: Gerar Executavel do Visualizador
      run: |
        pyinstaller --noconfirm --onefile --windowed --name VISUALIZAR_CATALOGO visualizar_catalogo.py

    - name: Criar Zip dos Executaveis
      run: |
        powershell Compress-Archive -Path dist/GERAR_CATALOGO.exe, dist/VISUALIZAR_CATALOGO.exe -DestinationPath Executaveis.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Executaveis-Windows
        path: Executaveis.zip
